Added encrypt_deterministic & randomize function.
jellevos/scicrypt pull request #44
Opened 2022-09-08 09:54 UTC by ArminZahedani

This PR adds functions `encrypt_deterministic` and `randomize` to the cryptosystems. This is useful when you want to control the randomness used e.g. for zero-knowledge proofs, or if you just want to add fresh randomness to your ciphertexts.

Changes:
- Added functions `encrypt_deterministic` and `randomize` to `cryptosystems.rs`. The default implementation of randomize is just to release the original ciphertext again, which is useful for cryptosystems not relying on Randomness (RSA).
- Added the above mentioned functions to the cryptosystems.
- Optimized as much as possible the operations needed using 1 or 0 as the deterministic randomness which cancels out a lot of terms.

Problems:
- The default behavior of randomize is to just return the ciphertext, which is useful for RSA. However, this forces to use `#[allow(unused_variables)]` above `randomize` so that the compiler does not complain. Not sure if you have a better idea to fix that.

2022-09-09 07:09 UTC, jellevos requested changes
Nice! Let's merge this one before the big backend refactor, but before that, we have to look carefully at the new trait functions.

2022-09-09 07:09 UTC, jellevos commented on scicrypt-traits/src/cryptosystems.rs
> +    fn encrypt_determinstic(&self, plaintext: &Self::Plaintext) -> Self::Ciphertext;
I think we should change it to something like `encrypt_trivial`. What do you think?

2022-09-09 07:09 UTC, jellevos commented on scicrypt-traits/src/cryptosystems.rs
> +    fn randomize(
I have two concerns right now about the `randomize` method:
1. For rerandomization in homomorphic encryption we typically do not care about the exact randomness used. For this reason, I would propose that `randomize` only takes a ciphertext as input. I would then create another method e.g. `randomize_with` that would also accept `randomness` as an argument.
2. I am afraid that this function signature will not be suitable for all cryptosystems because there exist schemes that use more than one 'piece' of randomness. So one solution would be to create another associated type to denote the randomness of a scheme.

Finally, I was wondering, do you think your use cases would still work if `randomize` would simply return the randomness it generated itself? In that case, that might be a less dangerous function signature.

I am curious to hear your thoughts!

2022-09-09 09:23 UTC, ArminZahedani commented on scicrypt-traits/src/cryptosystems.rs
> +    fn randomize(
Yes, both concerns make sense.
1. So implement a new method `randomize_with` that takes as input the actual randomness used. `randomize` would then call `randomize_with` but generate the randomness itself?
2. So you imagine to define a new associated type `type Randomness;` and each cryptosystem defines it? Any cryptosystem that would need e.g 2 random pieces could then use `type Randomness = [<randomness>; 2]`?

I think its possible with my current use case to have `randomize` return the randomness. However, it would be more flexible to be able to control the randomness used yourself. E.g. the bulletproofs crate requires you to put your own randomness.

I'll change the RSA one :)

2022-09-09 09:24 UTC, ArminZahedani commented on scicrypt-traits/src/cryptosystems.rs
> +    fn encrypt_determinstic(&self, plaintext: &Self::Plaintext) -> Self::Ciphertext;
Perhaps the original `encrypt_without_randomness` is the most descriptive?

2022-09-09 09:35 UTC, jellevos commented on scicrypt-traits/src/cryptosystems.rs
> +    fn randomize(
Exactly, I agree with both of your answers! And I agree that it is indeed more flexible if `randomize` lets you provide your own randomness.

2022-09-09 09:38 UTC, jellevos commented on scicrypt-traits/src/cryptosystems.rs
> +    fn encrypt_determinstic(&self, plaintext: &Self::Plaintext) -> Self::Ciphertext;
Hmm yeah, that might be the best so far. I am looking for something that sounds dangerous so people don't misuse it 😛

2022-09-09 10:25 UTC, ArminZahedani commented on scicrypt-traits/src/cryptosystems.rs
> +    fn randomize(
So I managed the points with `randomize_with` and `randomize`, and actually noticed that `encrypt_raw` always looks the same (i.e. first `encrypt_without_randomness` then `randomize`), except for RSA. We can get rid of some code duplication if `randomize` doesn't panic but just returns the ciphertexts for RSA, since then `encrypt_raw` can be defined in `cryptosystems.rs`. So we have two options:
1. Not panic for RSA but just return the ciphertext. This is slightly misleading for RSA but removes some code duplication.
2. Implement `encrypt_raw` for all cryptosystems separately, where 3/4 look the same. This is more exact, but is a bit more code to maintain

What do you think?

2022-09-09 13:03 UTC, jellevos commented on scicrypt-traits/src/cryptosystems.rs
> +    fn randomize(
Forgive me if I misunderstand, but I think the most sensible option is to:
- Let the default implementation of `encrypt_raw` call `encrypt_without_randomness` and then `randomize`
- Let RSA override `encrypt_raw` to only call `encrypt_without_randomness`

I do not think there is more code to maintain because the real encrypt code is only done once.

I think your option 1 is a bit dangerous because it would mean that when you call `randomize` on an RSA ciphertext, nothing happens.

2022-09-09 17:25 UTC, jellevos reviewed
Almost there 😄

2022-09-09 17:25 UTC, jellevos commented on scicrypt-he/src/cryptosystems/integer_el_gamal.rs
>      /// Encrypts an integer using the public key.
These doc comments seem to be above the wrong method now. Could you check?

2022-09-09 17:25 UTC, jellevos commented on scicrypt-he/src/cryptosystems/curve_el_gamal.rs
> +        let message = self.encrypt_without_randomness(plaintext);
I think we can omit this implementation and simply use the default.

2022-09-09 21:28 UTC, ArminZahedani commented on scicrypt-he/src/cryptosystems/integer_el_gamal.rs
>      /// Encrypts an integer using the public key.
Yea, they are not really correct... We can replace the method tested with `encrypt_without_randomness` and adjust the comment, but that is also somewhat confusing...? Or do you just want to adjust the comment ?

2022-09-10 18:19 UTC, jellevos commented on scicrypt-he/src/cryptosystems/integer_el_gamal.rs
>      /// Encrypts an integer using the public key.
I moved the code example to the module page instead and changed the rustdoc for `encrypt_without_randomness`.

2022-09-10 18:20 UTC, jellevos approved these changes

2022-09-10 18:38 UTC, merged